# Generated by Django 2.1.1 on 2018-10-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0002_auto_20181018_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
